// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvrZqwW5Xh9lgbkxskzdUoO0jIoEiBcE',
    appId: '1:385900695408:web:d34a4979ff9da26680c9b5',
    messagingSenderId: '385900695408',
    projectId: 'shrine-app-b9a7e',
    authDomain: 'shrine-app-b9a7e.firebaseapp.com',
    storageBucket: 'shrine-app-b9a7e.firebasestorage.app',
    measurementId: 'G-4V0940Z5X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUTf2u9G61vsETHJeyjfzptatOv-0LrM',
    appId: '1:385900695408:android:1073f5aef28c334180c9b5',
    messagingSenderId: '385900695408',
    projectId: 'shrine-app-b9a7e',
    storageBucket: 'shrine-app-b9a7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkC1YQR2R8NFioaRqzR7k5DrgdaEolrsI',
    appId: '1:385900695408:ios:1e368c31d497fe4180c9b5',
    messagingSenderId: '385900695408',
    projectId: 'shrine-app-b9a7e',
    storageBucket: 'shrine-app-b9a7e.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkC1YQR2R8NFioaRqzR7k5DrgdaEolrsI',
    appId: '1:385900695408:ios:1e368c31d497fe4180c9b5',
    messagingSenderId: '385900695408',
    projectId: 'shrine-app-b9a7e',
    storageBucket: 'shrine-app-b9a7e.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvrZqwW5Xh9lgbkxskzdUoO0jIoEiBcE',
    appId: '1:385900695408:web:c24c69bca05fe2a780c9b5',
    messagingSenderId: '385900695408',
    projectId: 'shrine-app-b9a7e',
    authDomain: 'shrine-app-b9a7e.firebaseapp.com',
    storageBucket: 'shrine-app-b9a7e.firebasestorage.app',
    measurementId: 'G-WPMSHDJD2F',
  );
}
